export const SET_DEVICELIST = 'SET/DEVICELIST';
export const SET_SYSTEMINFO = 'SET/SYSTEMINFO';
export const UPDATE_DEVICELIST = 'UPDATE/DEVICELIST';
export const SET_CONFIRMBTNSTATE = 'SET/CONFIRMBTNSTATE';
