export const SET_LUCKYSTATUS = 'LUCKYDRAW/SETSTATUS';
export const SET_LUCKYDATA = 'LUCKYDRAW/SETDATA';

export const SET_VOTESTATUS = 'VOTE/SETSTATUS';
export const SET_VOTEDATA = 'VOTE/SETDATA';

export const SET_ANSWERSTATUS = 'ANSWER/SETSTATUS';
export const SET_ANSWERDATA = 'ANSWER/SETDATA';

export const SET_SHARESTATUS = 'SHARE/SETSTATUS';
export const SET_SHAREDATA = 'SHARE/SETDATA';

export const SET_CALLROLLSTATUS = 'CALLROLL/SETSTATUS';
export const SET_CALLROLLDATA = 'CALLROLL/SETDATA';

export const SET_ANNOUNCEMENTSTATUS = 'ANNOUNCEMENT/SETSTATUS';
export const SET_ANNOUNCEMENTDATA = 'ANNOUNCEMENT/SETDATA';

export const SET_CLOSECALLROLL = 'CLOSE/CALLROLL';

export const SET_LUCKYCOUNTNUM = 'LUCKYDRAW/COUNTNUM';

export const SET_UPDATAPICTURE = 'UPDATAPICTURE';

export const SET_MOBILE_PAGE_ZZC = 'SET_MOBILE_PAGE_ZZC'; // 移动端遮罩层

export const SET_MP4_FULL = 'SET_MP4_FULL'; // mp4是否全屏

export const INIT_MODULES_STATE = 'INIT_MODULES_STATE';

export const SET_APPLY_WHEAT = 'SET_APPLY_WHEAT'; // 是否为上麦按钮

export const SET_MCRO_PLAY = 'SET_MCRO_PLAY'; // 麦克风是否播放过音频
