export const SET_IS_FULLSCREEN = 'SET_IS_FULLSCREEN';

export const SET_WHITE_BOARD_LAY = 'SET_WHITE_BOARD_LAY';

export const SET_WB_VIDEOSTATUS = 'SET_WB_VIDEOSTATUS';

export const SET_WB_MP3_STATUS = 'SET_WB_MP3_STATUS';
